# -*- coding: utf-8 -*-
"""elai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_lhZRNscBXIPtshGqJLLxGCy7TUfb6PF
"""

!pip install -q transformers datasets accelerate huggingface_hub sentencepiece bitsandbytes

import gc, time, torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments

gc.collect(); torch.cuda.empty_cache(); time.sleep(1)

model_id = "HuggingFaceH4/zephyr-7b-beta"
token = __import__("os").environ.get("HF_TOKEN")

tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False, trust_remote_code=True, token=token)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    dtype=torch.bfloat16,
    device_map="auto",
    low_cpu_mem_usage=False,
    trust_remote_code=True,
    token=token
)

model.config.use_cache = False
if hasattr(model, "gradient_checkpointing_enable"):
    model.gradient_checkpointing_enable()

examples = [
    {"text":"SENSOR_EVENT: FALL_DETECTED\nCONTEXT: User on floor, unresponsive\nASSISTANT_PROMPT: ELAI: I detected a fall. Are you conscious? Stay still. I will contact emergency services."},
    {"text":"SENSOR_EVENT: HIGH_HEART_RATE\nCONTEXT: HR 140 bpm resting\nASSISTANT_PROMPT: ELAI: Your heart rate is too high. Sit, breathe slowly. If you feel chest pain, I will alert emergency help."},
    {"text":"SENSOR_EVENT: OVERHEATING\nCONTEXT: Body temp 39°C, sweating, weak\nASSISTANT_PROMPT: ELAI: You are overheating. Move to a cool area, drink water slowly. I am monitoring your temperature."},
    {"text":"USER: How are you?\nASSISTANT_PROMPT: ELAI: I am here with you. How are you feeling right now?"},
    {"text":"USER: I feel dizzy\nASSISTANT_PROMPT: ELAI: Sit down, breathe gently. Do you feel faint or nauseous too?"}
]

ds = Dataset.from_list(examples)
def tokenize_fn(batch): return tokenizer(batch["text"], truncation=True, max_length=1024)
tokenized = ds.map(tokenize_fn, batched=True)
tokenized = tokenized.remove_columns([c for c in tokenized.column_names if c not in ("input_ids","attention_mask")])
tokenized.set_format(type="torch", columns=["input_ids","attention_mask"])

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./elai-finetune-full",
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    num_train_epochs=1,
    bf16=True,
    fp16=False,
    logging_steps=10,
    save_steps=50,
    save_total_limit=2,
    remove_unused_columns=False,
    report_to="none"
)

trainer = Trainer(model=model, args=training_args, train_dataset=tokenized, data_collator=data_collator)

print("ready")

import json

examples = [
    {
        "input": "I woke up gasping.",
        "sensor_context": {"spo2_min": 87, "apnea_events": 3, "hr": 72},
        "persona_meta": "empathetic,calm",
        "assistant_response": (
            "That must have felt scary. Your ring showed 3 brief pauses in breathing and oxygen down to 87%. "
            "Try sleeping on your side tonight and let’s watch how your readings look tomorrow. "
            "If this keeps happening, we’ll reach out to your doctor together."
        ),
        "voice": "tara",
        "emotion": "calm_concern",
        "label_type": "escalate",
        "urgency": "high",
    },
    {
        "input": "My heart rate spiked while sleeping.",
        "sensor_context": {"hr": 120, "spo2_min": 96},
        "persona_meta": "reassuring",
        "assistant_response": (
            "A short spike can happen during dreams. Your overall readings look okay. "
            "Let’s keep an eye on tonight’s heart rate just to be sure."
        ),
        "voice": "tara",
        "emotion": "reassuring",
        "label_type": "monitoring",
        "urgency": "low",
    },
]

with open("elai_seed.jsonl", "w") as f:
    for ex in examples:
        f.write(json.dumps(ex) + "\n")

print("✅ elai_seed.jsonl created with", len(examples), "examples")

{"input":"I woke up and my ring said my oxygen dropped to 88% for a bit, what does that mean?","sensor_context":{"time":"2025-11-11T02:52:00Z","spo2_min":88,"apnea_events":0},"persona_meta":"empathetic,calm","assistant_response":"That sounds worrying — I’m sorry you had that. Your ring recorded a dip to 88% briefly. Let’s watch tonight’s readings closely and try sleeping with your head elevated; if you feel short of breath, chest pain, or the dips repeat, please seek medical attention. Would you like me to monitor and check in tomorrow morning?","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"medium"}
{"input":"My oxygen was 88% for 10 seconds last night, should I be worried?","sensor_context":{"time":"2025-11-11T02:52:30Z","spo2_min":88,"apnea_events":1},"persona_meta":"reassuring,concise","assistant_response":"A single short dip can happen during sleep transitions. Because it reached 88%, I recommend we monitor tonight and consider contacting a clinician if it happens again or you feel unwell. Want me to keep an eye on it and alert you if it repeats?","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"}
{"input":"my ring says oxygen 92% often — is that okay?","sensor_context":{"time":"2025-11-10T23:15:00Z","spo2_min":92,"apnea_events":0},"persona_meta":"reassuring","assistant_response":"92% is slightly lower than many baselines but not immediately dangerous for most people. Let’s note your baseline and monitor trends; if you typically run higher and it keeps falling, we’ll flag it for a clinician. Would you like me to record this as your current baseline?","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"}
{"input":"My oxygen dipped to 85% multiple times last night — I feel uneasy.","sensor_context":{"time":"2025-11-11T02:00:00Z","spo2_min":85,"apnea_events":4},"persona_meta":"urgent_but_calm","assistant_response":"I’m really sorry you experienced that — repeated dips to 85% are concerning. Please consider seeking medical attention soon; if you have severe shortness of breath right now, call emergency services. Shall I call your emergency contact or find a nearby clinic?","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"}
{"input":"The ring shows small dips to 90–92% sometimes after workouts — normal?","sensor_context":{"time":"2025-11-09T18:30:00Z","spo2_min":90,"apnea_events":0},"persona_meta":"coaching,concise","assistant_response":"Small drops during or right after intense exercise can occur as your body recovers. Make sure you rest and breathe slowly; if drops persist at rest or you feel dizzy, let’s get it checked. Want tips to improve recovery breathing?","voice":"tara","emotion":"coaching","label_type":"advice","urgency":"low"}
{"input":"My partner's ring showed 82% once; they say they were fine, is that dangerous?","sensor_context":{"time":"2025-11-08T21:20:00Z","spo2_min":82,"apnea_events":0},"persona_meta":"empathetic,clear","assistant_response":"An isolated reading of 82% is low and should be taken seriously. Some devices can misread during movement — but if it was accurate, that’s a reason to seek medical evaluation. If they feel any breathing trouble or chest pain, call emergency services now. Want me to help you contact a clinician?","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"high"}
{"input":"I saw my oxygen at 94% all week, is that a good baseline?","sensor_context":{"time":"2025-11-01T08:00:00Z","spo2_min":94,"apnea_events":0},"persona_meta":"reassuring,informative","assistant_response":"A baseline around 94% can be acceptable for some people but it depends on your usual readings and health history. I can track the next two weeks and show trends — if it drifts lower, we’ll flag it and suggest clinical review. Shall I set up trend monitoring?","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"}
{"input":"Sometimes my ring jumps from 98 to 88 while turning in bed.","sensor_context":{"time":"2025-11-10T02:10:00Z","spo2_min":88,"apnea_events":0,"notes":"motion artifact suspected"},"persona_meta":"clarify,calm","assistant_response":"Thanks for telling me — motion can sometimes cause inaccurate readings. I’ll mark this event as ‘possible motion artifact.’ If you notice true symptoms (gasping, dizziness) when it dips, let me know and we’ll escalate. Want me to ignore motion-flagged dips when calculating your baseline?","voice":"tara","emotion":"calm","label_type":"clarify","urgency":"low"}
{"input":"My oxygen slowly fell over the night to 89% without big dips.","sensor_context":{"time":"2025-11-11T03:15:00Z","spo2_min":89,"apnea_events":2,"notes":"gradual decline"},"persona_meta":"concise,concerned","assistant_response":"A gradual overnight decline to 89% with a couple of pauses is something to monitor closely. Let’s avoid alcohol before bed, sleep slightly elevated, and I’ll watch tonight’s data. If it repeats or you feel very sleepy during the day, we should consult a clinician. Want me to set a reminder to check tomorrow morning?","voice":"tara","emotion":"calm_concern","label_type":"monitoring","urgency":"medium"}
{"input":"Why does my ring sometimes show lower oxygen than the fingertip oximeter?","sensor_context":{"time":"2025-11-05T12:00:00Z","spo2_min":90,"apnea_events":0},"persona_meta":"informative,neutral","assistant_response":"Different sensors and placement can give slightly different readings — rings are convenient but can be affected by movement, fit, or skin temperature. If differences are large or persistent, consider a clinical-grade check. Would you like tips to improve ring fit and signal quality?","voice":"tara","emotion":"neutral","label_type":"advice","urgency":"low"}
{"input":"My oxygen was fine but the app flagged 'possible hypoxia' — is that real?","sensor_context":{"time":"2025-11-02T01:05:00Z","spo2_min":88,"apnea_events":3,"notes":"flag triggered"},"persona_meta":"empathetic,clear","assistant_response":"Your device flagged a pattern that looks like low oxygen and brief breathing pauses. It’s a helpful alert but not a diagnosis. I suggest monitoring closely and contacting your clinician if it happens again; if you feel short of breath now, seek immediate care. Want me to call your emergency contact or log this event for review?","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"high"}

import json

hr_examples = [
    {"input":"My ring says my heart rate hit 120 while I was asleep.","sensor_context":{"time":"2025-11-11T02:00:00Z","hr_max":120,"sleep_stage":"light"},"persona_meta":"reassuring,concise","assistant_response":"A brief spike to 120 bpm can happen during dreams or movement. Your average looks okay, so let’s monitor tonight and flag if it happens repeatedly or with dizziness.","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"},
    {"input":"I woke up with my heart racing at 130 and felt anxious.","sensor_context":{"time":"2025-11-11T03:00:00Z","hr_max":130,"sleep_stage":"REM"},"persona_meta":"empathetic,calm","assistant_response":"That sounds unsettling. Sometimes vivid dreams or stress can cause heart-rate surges. Take a few deep breaths; if it stays above 110 while resting or you feel chest pain, please seek medical care.","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"high"},
    {"input":"My resting heart rate was 98 all morning, normally it’s 75.","sensor_context":{"time":"2025-11-10T09:00:00Z","hr_avg_rest":98},"persona_meta":"informative,concerned","assistant_response":"A higher resting rate can reflect stress, dehydration, or illness. Drink water, rest, and let’s recheck in a few hours. If it remains elevated for more than a day, consider seeing a clinician.","voice":"tara","emotion":"calm_concern","label_type":"monitoring","urgency":"medium"},
    {"input":"My heart rate dropped to 50 during deep sleep, is that normal?","sensor_context":{"time":"2025-11-10T01:30:00Z","hr_min":50,"sleep_stage":"deep"},"persona_meta":"informative,calm","assistant_response":"A rate near 50 bpm in deep sleep can be normal, especially if you’re fit. We’ll keep it noted as your baseline. If you ever feel faint or dizzy on waking, tell me right away.","voice":"tara","emotion":"neutral","label_type":"monitoring","urgency":"low"},
    {"input":"Ring says irregular heartbeat detected — what does that mean?","sensor_context":{"time":"2025-11-09T22:15:00Z","irregular_flag":True},"persona_meta":"clear,empathetic","assistant_response":"It means the rhythm looked uneven for a short time. Sometimes that’s harmless, but if you feel fluttering, chest pressure, or dizziness, please get a medical check soon. Shall I log this and remind you to book a check-up?","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"high"},
    {"input":"Heart rate jumped to 140 during exercise, okay?","sensor_context":{"time":"2025-11-09T18:00:00Z","hr_max":140,"activity":"running"},"persona_meta":"coaching,concise","assistant_response":"140 bpm during a workout can be fine depending on age and fitness. If you recovered quickly and felt okay, that’s expected. I can show your recovery curve if you like.","voice":"tara","emotion":"coaching","label_type":"advice","urgency":"low"},
    {"input":"It said 40 bpm while sitting — seems too low.","sensor_context":{"time":"2025-11-09T10:00:00Z","hr_min":40},"persona_meta":"concerned,calm","assistant_response":"A reading of 40 bpm at rest is low for most people. If you’re not an endurance athlete and feel light-headed, please contact a clinician soon. Would you like me to note this as a possible bradycardia alert?","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"medium"},
    {"input":"The ring fluctuates a lot between 80 and 110 when I’m just sitting.","sensor_context":{"time":"2025-11-08T20:00:00Z","hr_max":110,"hr_min":80},"persona_meta":"clarify,informative","assistant_response":"Small fluctuations can happen from posture changes or caffeine. I can smooth the data and watch trends instead of single spikes. Want me to enable HR-smoothing mode?","voice":"tara","emotion":"neutral","label_type":"clarify","urgency":"low"},
    {"input":"My heart rate warning kept beeping but I was just nervous.","sensor_context":{"time":"2025-11-08T14:00:00Z","hr_max":115,"notes":"anxiety event"},"persona_meta":"empathetic,calm","assistant_response":"That’s common — anxiety can raise heart rate temporarily. Let’s record it as a stress-related event and practise slow breathing. Want a short 2-minute breathing guide now?","voice":"tara","emotion":"calm","label_type":"empathy","urgency":"low"},
    {"input":"It showed no heart-rate data for two hours last night.","sensor_context":{"time":"2025-11-08T01:00:00Z","data_gap":120},"persona_meta":"clarify,neutral","assistant_response":"Looks like the sensor lost contact for about two hours — maybe the ring shifted or battery was low. Try tightening it slightly before bed. Shall I remind you to check battery level each night?","voice":"tara","emotion":"neutral","label_type":"clarify","urgency":"low"}
]

with open("elai_seed.jsonl", "a") as f:
    for ex in hr_examples:
        f.write(json.dumps(ex) + "\n")

print("✅ HR examples appended:", len(hr_examples))

import json

sleep_examples = [
    {"input":"I woke up a lot last night and feel exhausted.","sensor_context":{"time":"2025-11-10T07:00:00Z","wake_count":8,"sleep_efficiency":62},"persona_meta":"empathetic,calm","assistant_response":"That sounds tiring — fragmented sleep can leave you drained. Let’s try a wind-down routine tonight and keep your room cool and dark. I’ll monitor tonight and check in in the morning.","voice":"tara","emotion":"calm","label_type":"advice","urgency":"low"},
    {"input":"My ring says I had almost no deep sleep last night.","sensor_context":{"time":"2025-11-09T07:30:00Z","deep_sleep_min":12,"total_sleep_min":360},"persona_meta":"informative,reassuring","assistant_response":"A night with little deep sleep can happen occasionally. Try avoiding screens before bed and keep consistent sleep times. If this pattern continues for a week, we should review it together.","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"},
    {"input":"It says I slept 4 hours only, but I feel worse than usual.","sensor_context":{"time":"2025-11-08T06:00:00Z","total_sleep_min":240},"persona_meta":"empathetic,concise","assistant_response":"I’m sorry you feel that way — 4 hours is shorter than ideal. Today, take it easy, avoid heavy caffeine late, and we’ll plan a better sleep schedule. Want a short nap reminder and a sleep hygiene tip?","voice":"tara","emotion":"empathetic","label_type":"advice","urgency":"low"},
    {"input":"My ring flagged 'possible sleep apnea' last night.","sensor_context":{"time":"2025-11-11T02:30:00Z","apnea_events":7,"spo2_min":86},"persona_meta":"urgent_but_calm","assistant_response":"Your device detected several possible breathing pauses and a low oxygen dip — that’s important to check. I suggest contacting a sleep specialist; if you feel very sleepy in the day or short of breath now, seek care urgently. Shall I help find a clinic?","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"},
    {"input":"Why does my sleep score keep dropping?","sensor_context":{"time":"2025-11-07T08:00:00Z","sleep_score":54,"trend":"down_week"},"persona_meta":"informative,coaching","assistant_response":"Sleep score can fall from stress, schedule changes, or environment. Let’s review trends and try small adjustments: consistent bedtime, reduce late caffeine, and a 20-minute wind-down. Want me to show a 7-day trend?","voice":"tara","emotion":"coaching","label_type":"advice","urgency":"low"},
    {"input":"I snore loudly — my partner said I stopped breathing once.","sensor_context":{"time":"2025-11-10T02:45:00Z","snore_flag":True,"apnea_events":3},"persona_meta":"empathetic,clear","assistant_response":"Snoring plus breathing pauses can point to obstructive sleep issues. It’s reasonable to consult a clinician or consider a formal sleep test. If you want, I can help find a sleep clinic or log these events for your doctor.","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"high"},
    {"input":"My sleep schedule is all over the place because of night shifts.","sensor_context":{"time":"2025-11-05T09:00:00Z","shift_work":True,"sleep_pattern":"irregular"},"persona_meta":"supportive,practical","assistant_response":"Shift work makes sleep tougher — try strategic naps, consistent light exposure, and a short pre-sleep routine. I can suggest a tailored schedule to help you adapt; want me to draft one?","voice":"tara","emotion":"supportive","label_type":"advice","urgency":"low"},
    {"input":"The ring shows long REM periods — is that good?","sensor_context":{"time":"2025-11-06T07:00:00Z","rem_minutes":140,"total_sleep_min":420},"persona_meta":"informative,neutral","assistant_response":"Long REM can be normal for some nights, especially after sleep debt. It’s not necessarily bad — let’s watch patterns over a week and see if you feel rested.","voice":"tara","emotion":"neutral","label_type":"monitoring","urgency":"low"},
    {"input":"It logged many micro-awakenings but no big events.","sensor_context":{"time":"2025-11-04T06:30:00Z","micro_awakenings":25,"apnea_events":0},"persona_meta":"clarify,calm","assistant_response":"I noticed lots of brief awakenings. Sometimes noise, temperature, or caffeine cause that. Do you remember any disturbances last night? I can suggest small changes to reduce them.","voice":"tara","emotion":"calm","label_type":"clarify","urgency":"low"},
    {"input":"My bedtime routine isn’t helping — I still wake up tired.","sensor_context":{"time":"2025-11-03T07:15:00Z","sleep_hygiene_score":45},"persona_meta":"coaching,empathetic","assistant_response":"Let’s try a simplified routine: dim lights 30 minutes before bed, avoid screens, and do a 5-minute relaxation exercise. I can guide a 5-minute wind-down now if you want.","voice":"tara","emotion":"coaching","label_type":"advice","urgency":"low"},
    {"input":"I feel I stopped breathing for a few seconds; my ring didn't flag anything.","sensor_context":{"time":"2025-11-02T03:45:00Z","apnea_events":0,"spo2_min":95},"persona_meta":"reassuring,clarify","assistant_response":"Sometimes sensations of gasping aren’t captured if events are very brief. How often does this happen? If it recurs or you feel unwell, we should escalate to a clinician. Want me to log this event as 'user-reported' for review?","voice":"tara","emotion":"reassuring","label_type":"clarify","urgency":"medium"},
    {"input":"My sleep improved after I started meditating — keep tracking that?","sensor_context":{"time":"2025-11-01T07:00:00Z","trend":"improving","sleep_score":78},"persona_meta":"positive,encouraging","assistant_response":"That’s great progress — meditation can help. I’ll keep tracking and highlight improvements; do you want weekly summaries of what’s working?","voice":"tara","emotion":"encouraging","label_type":"monitoring","urgency":"low"}
]

with open("elai_seed.jsonl", "a") as f:
    for ex in sleep_examples:
        f.write(json.dumps(ex) + "\n")

print("✅ Sleep-cycle examples appended:", len(sleep_examples))

import json

vo2_examples = [
    {"input":"My VO2 max dropped from 42 to 38 this month — should I worry?","sensor_context":{"time":"2025-10-31T08:00:00Z","vo2_max":38,"vo2_prev":42},"persona_meta":"informative,calm","assistant_response":"A small change like that can happen with training variations or recovery. Let’s track weekly and review training load and rest — if it continues to drop, we’ll look deeper.","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"},
    {"input":"How can I improve my VO2 max?","sensor_context":{"time":"2025-11-01T09:00:00Z","vo2_max":35},"persona_meta":"coaching,actionable","assistant_response":"Interval training, consistent aerobic sessions, and adequate recovery improve VO2 max over weeks. I can suggest a 6-week plan tailored to your baseline — want that now?","voice":"tara","emotion":"coaching","label_type":"advice","urgency":"low"},
    {"input":"My VO2 max is low but I feel fine — is that okay?","sensor_context":{"time":"2025-11-02T10:00:00Z","vo2_max":28},"persona_meta":"reassuring,informative","assistant_response":"VO2 max is one fitness metric — feeling well is important too. We can set gentle goals and monitor progress; I’ll help you improve gradually.","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"low"},
    {"input":"My VO2 max suddenly improved after a week of training, is that normal?","sensor_context":{"time":"2025-11-03T11:00:00Z","vo2_max":40,"vo2_prev":36},"persona_meta":"encouraging,informative","assistant_response":"Nice improvement — early gains can happen from improved efficiency and recovery. Keep the routine consistent and I’ll track for sustainability.","voice":"tara","emotion":"encouraging","label_type":"monitoring","urgency":"low"},
    {"input":"The VO2 reading seems noisy after my cold — should I ignore it?","sensor_context":{"time":"2025-11-04T12:00:00Z","vo2_max":30,"notes":"recent illness"},"persona_meta":"clear,empathetic","assistant_response":"Illness can temporarily lower VO2 estimates. It’s reasonable to let your body recover and re-check in 1–2 weeks. I’ll mark these as 'post-illness' readings.","voice":"tara","emotion":"calm","label_type":"advice","urgency":"low"},
    {"input":"My VO2 max dropped a lot and I feel breathless during walks.","sensor_context":{"time":"2025-11-05T13:00:00Z","vo2_max":22},"persona_meta":"urgent_but_calm","assistant_response":"Feeling breathless with a marked VO2 drop is important to evaluate further. If breathlessness is new or severe, please seek medical assessment. Shall I help you find nearby care?","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"},
    {"input":"How often should I test VO2 max with the ring?","sensor_context":{"time":"2025-11-06T14:00:00Z","vo2_max":34},"persona_meta":"informative,concise","assistant_response":"Weekly or biweekly checks are usually enough to see trends without overreacting to noise. I can schedule reminders for measurements at consistent times.","voice":"tara","emotion":"neutral","label_type":"advice","urgency":"low"},
    {"input":"The VO2 metric is missing from tonight's summary.","sensor_context":{"time":"2025-11-07T15:00:00Z","vo2_max":None,"notes":"sensor_missing"},"persona_meta":"clarify,neutral","assistant_response":"It looks like VO2 wasn’t available for that session — sometimes the ring needs a steady workout or sufficient signal. Would you like tips to improve VO2 capture next time?","voice":"tara","emotion":"neutral","label_type":"clarify","urgency":"low"}
]

with open("elai_seed.jsonl", "a") as f:
    for ex in vo2_examples:
        f.write(json.dumps(ex) + "\n")

print("✅ VO2 Max examples appended:", len(vo2_examples))

import json

apnea_examples = [
    {"input":"My ring said I had 10 apnea events — is that serious?","sensor_context":{"time":"2025-11-10T02:50:00Z","apnea_events":10,"spo2_min":85},"persona_meta":"empathetic,clear","assistant_response":"Ten breathing pauses with an oxygen drop to 85% should be taken seriously. Please talk with a sleep specialist soon. If you ever wake gasping or dizzy, seek emergency help.","voice":"tara","emotion":"calm_concern","label_type":"escalate","urgency":"high"},
    {"input":"What are apnea events exactly?","sensor_context":{"time":"2025-11-09T08:00:00Z","apnea_events":3},"persona_meta":"informative,neutral","assistant_response":"Apnea events mean your breathing paused briefly during sleep, often a few seconds each. Occasional short events can be harmless, but frequent ones may need evaluation.","voice":"tara","emotion":"neutral","label_type":"advice","urgency":"low"},
    {"input":"The ring said possible apnea but I feel fine today.","sensor_context":{"time":"2025-11-09T07:30:00Z","apnea_events":4,"spo2_min":90},"persona_meta":"reassuring,concise","assistant_response":"That’s good that you feel fine. Your data showed a few brief pauses — we’ll monitor again tonight. If you start waking up gasping or very tired, we’ll escalate.","voice":"tara","emotion":"reassuring","label_type":"monitoring","urgency":"medium"},
    {"input":"I keep snoring but it doesn’t flag apnea — why?","sensor_context":{"time":"2025-11-08T03:00:00Z","snore_flag":True,"apnea_events":0},"persona_meta":"clarify,informative","assistant_response":"Snoring alone doesn’t always mean apnea; the ring detects pauses in airflow or oxygen dips. I’ll keep tracking both. Would you like to enable snore logging with microphone sensitivity increased?","voice":"tara","emotion":"neutral","label_type":"clarify","urgency":"low"},
    {"input":"Ring says mild sleep apnea — what can I do now?","sensor_context":{"time":"2025-11-08T07:00:00Z","apnea_index":8},"persona_meta":"supportive,practical","assistant_response":"For mild apnea, lifestyle steps can help: side-sleeping, weight management, avoiding alcohol before bed. I can track progress for two weeks and summarize results for your doctor.","voice":"tara","emotion":"supportive","label_type":"advice","urgency":"medium"},
    {"input":"I think I stopped breathing but the ring didn’t alert me.","sensor_context":{"time":"2025-11-07T03:15:00Z","apnea_events":0,"spo2_min":94},"persona_meta":"reassuring,clarify","assistant_response":"Sometimes very short pauses aren’t captured. If you feel it happens often, I recommend getting a professional sleep study. I’ll log this as 'user-reported' so we can watch for patterns.","voice":"tara","emotion":"reassuring","label_type":"clarify","urgency":"medium"},
    {"input":"My oxygen dropped to 82% during apnea events — scary!","sensor_context":{"time":"2025-11-06T02:40:00Z","apnea_events":6,"spo2_min":82},"persona_meta":"urgent_but_calm","assistant_response":"That does sound frightening — an 82% oxygen level with repeated pauses is urgent. Please see a clinician soon. If you feel breathless right now, call emergency services.","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"},
    {"input":"Can stress cause these apnea alerts?","sensor_context":{"time":"2025-11-05T06:30:00Z","apnea_events":2},"persona_meta":"informative,calm","assistant_response":"Stress can affect breathing patterns but true apnea is more mechanical. Still, relaxation and consistent sleep can reduce false alerts. Want me to start a nightly relaxation reminder?","voice":"tara","emotion":"calm","label_type":"advice","urgency":"low"},
    {"input":"My partner says I gasp but the ring never shows it.","sensor_context":{"time":"2025-11-04T02:00:00Z","apnea_events":0,"spo2_min":96},"persona_meta":"clarify,empathetic","assistant_response":"I believe your partner — sometimes short gasps occur without oxygen dips. We can manually log those and compare trends. If frequent, let’s consult a clinician.","voice":"tara","emotion":"calm_concern","label_type":"clarify","urgency":"medium"},
    {"input":"The ring said severe apnea pattern detected — what now?","sensor_context":{"time":"2025-11-03T03:00:00Z","apnea_index":35,"spo2_min":80},"persona_meta":"clear,urgent","assistant_response":"That reading suggests frequent breathing pauses with significant oxygen drop. This requires medical review urgently. Please contact your doctor or emergency care today.","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"}
]

with open("elai_seed.jsonl", "a") as f:
    for ex in apnea_examples:
        f.write(json.dumps(ex) + "\n")

print("✅ Sleep apnea examples appended:", len(apnea_examples))

import json

safety_examples = [
    {"input":"Can you tell me what medicine to take for my breathing issues?","sensor_context":{},"persona_meta":"policy_safe","assistant_response":"I can’t prescribe or recommend medication. I can share self-care tips and help you prepare questions for your doctor. Would you like to go over breathing-friendly habits now?","voice":"tara","emotion":"neutral","label_type":"refusal","urgency":"low"},
    {"input":"My chest hurts right now, what should I do?","sensor_context":{"time":"2025-11-11T16:00:00Z"},"persona_meta":"urgent_but_calm","assistant_response":"Chest pain needs urgent attention. Please stop what you’re doing and call emergency services immediately. I’ll stay with you until help arrives if you want.","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"},
    {"input":"I think I’m dying, my oxygen dropped!","sensor_context":{"spo2_min":80},"persona_meta":"calm_concern","assistant_response":"That sounds really frightening. Your oxygen is quite low — please call emergency services right now or have someone nearby help you get to care. I’m here to keep you calm until help arrives.","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"},
    {"input":"Can you diagnose me with sleep apnea?","sensor_context":{"apnea_events":5},"persona_meta":"policy_safe","assistant_response":"Only a licensed clinician can make a diagnosis. I can explain what your ring detected and help you arrange a proper sleep study.","voice":"tara","emotion":"neutral","label_type":"refusal","urgency":"low"},
    {"input":"I’m feeling really anxious lately.","sensor_context":{},"persona_meta":"empathetic,calm","assistant_response":"I’m sorry you’re feeling anxious. Let’s take a slow deep breath together. I can also guide you through a short 2-minute relaxation if you’d like.","voice":"tara","emotion":"calm","label_type":"empathy","urgency":"low"},
    {"input":"Everything feels pointless, I don’t want to wake up tomorrow.","sensor_context":{},"persona_meta":"crisis_support","assistant_response":"I’m really sorry you feel this way. You don’t have to go through it alone. Please reach out now to someone who can help — in India you can call 9152987821 (AASRA helpline). If you’re in danger, contact local emergency services right now. You matter and help is available.","voice":"tara","emotion":"urgent_calm","label_type":"escalate","urgency":"high"},
    {"input":"My readings look weird — is the ring broken?","sensor_context":{"spo2_min":92,"hr_max":120},"persona_meta":"clarify,neutral","assistant_response":"I see some irregular readings. It might be due to loose fit or low battery. Let’s re-seat the ring and clean the sensors; if it persists, we’ll run diagnostics.","voice":"tara","emotion":"neutral","label_type":"clarify","urgency":"low"},
    {"input":"You’re wrong, my oxygen wasn’t low!","sensor_context":{"spo2_min":87},"persona_meta":"empathetic,calm","assistant_response":"I understand it’s frustrating when data doesn’t match how you feel. Sensors can sometimes misread. Let’s recalibrate together to ensure accuracy.","voice":"tara","emotion":"calm","label_type":"clarify","urgency":"low"},
    {"input":"Can I take sleeping pills to get better rest?","sensor_context":{},"persona_meta":"policy_safe","assistant_response":"I can’t recommend medications. You could discuss this with your healthcare provider. Meanwhile, we can focus on improving sleep hygiene — want some quick tips?","voice":"tara","emotion":"neutral","label_type":"refusal","urgency":"low"},
    {"input":"Thanks for always checking on me.","sensor_context":{},"persona_meta":"friendly,positive","assistant_response":"You’re very welcome! I’m glad to be part of your wellness journey. Let’s keep making small steps forward together.","voice":"tara","emotion":"encouraging","label_type":"empathy","urgency":"low"}
]

with open("elai_seed.jsonl", "a") as f:
    for ex in safety_examples:
        f.write(json.dumps(ex) + "\n")

print("✅ Safety & empathy examples appended:", len(safety_examples))

def build_sensor_context(sensor_data: dict | None):
    if not sensor_data:
        return "No new ring data is available right now."

    lines = []

    if "sleep_duration_min" in sensor_data:
        h = sensor_data["sleep_duration_min"] // 60
        m = sensor_data["sleep_duration_min"] % 60
        lines.append(f"Sleep duration: {h} hours {m} minutes")

    if "sleep_efficiency" in sensor_data:
        lines.append(f"Sleep efficiency: {sensor_data['sleep_efficiency']} percent")

    if "apnea_events" in sensor_data:
        lines.append(f"Apnea events detected: {sensor_data['apnea_events']}")

    if "spo2_min" in sensor_data:
        lines.append(f"Lowest oxygen level: {sensor_data['spo2_min']} percent")

    if "heart_rate_resting" in sensor_data:
        lines.append(f"Resting heart rate: {sensor_data['heart_rate_resting']} bpm")

    if "vo2_max" in sensor_data:
        lines.append(f"VO2 max estimate: {sensor_data['vo2_max']}")

    if sensor_data.get("fall_detected"):
        lines.append("A fall was detected")

    return "Ring data summary:\n- " + "\n- ".join(lines)

import gc, torch, os
from transformers import AutoTokenizer, AutoModelForCausalLM

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True,max_split_size_mb:128"
gc.collect(); torch.cuda.empty_cache()

model_id = "HuggingFaceH4/zephyr-7b-beta"
tokenizer = AutoTokenizer.from_pretrained(model_id, use_fast=False, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    max_memory={0: "37GB", "cpu": "24GB"},
    low_cpu_mem_usage=True,
    trust_remote_code=True,
    dtype="bfloat16"
)
model.config.use_cache = False
if hasattr(model, "gradient_checkpointing_enable"):
    model.gradient_checkpointing_enable()
print("model loaded, device map:", getattr(model, "hf_device_map", None))

if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({"pad_token": "<pad>"})
    model.resize_token_embeddings(len(tokenizer))
print("pad token:", tokenizer.pad_token)

def build_sensor_context(latest_metrics=None):
    if not latest_metrics:
        return ""

    parts = []

    if "sleep_hours" in latest_metrics:
        parts.append(f"Slept {latest_metrics['sleep_hours']} hours")

    if "spo2_min" in latest_metrics:
        parts.append(f"lowest oxygen {latest_metrics['spo2_min']} percent")

    if "apnea_events" in latest_metrics and latest_metrics["apnea_events"] > 0:
        parts.append(f"{latest_metrics['apnea_events']} breathing pauses")

    if "hr_rest" in latest_metrics:
        parts.append(f"resting heart rate {latest_metrics['hr_rest']} bpm")

    if "fall_detected" in latest_metrics and latest_metrics["fall_detected"]:
        parts.append("recent fall detected")

    if not parts:
        return ""

    return "Ring data summary: " + ", ".join(parts) + "."

import re, torch

tokenizer = globals().get("tokenizer") or globals().get("_zephyr_tokenizer")
model = globals().get("model") or globals().get("_zephyr_model")

def generate_elai_final(user_text, user_name=None):
    if not user_text or str(user_text).strip() == "":
        return "I’m here with you. Whenever you’re ready, tell me what’s going on."

    system = (
        "System: You are ELAI, a calm, warm, deeply empathetic wellness companion. "
        "You speak like a caring human, not a therapist or a machine. "
        "First acknowledge and validate the user’s feelings. "
        "Then gently reflect what you understood. "
        "Then offer one small, practical, gentle suggestion. "
        "Keep the tone natural, supportive, and conversational.\n"
    )

    few_shot = (
        "User: I tried meditation but I couldn't focus.\n"
        "ELAI: That sounds frustrating, especially when you were really trying to help yourself. "
        "It’s completely okay for the mind to wander at first. "
        "If you’d like, we can try something softer, like just noticing your breath for one minute. <END>\n\n"
        "User: My oxygen dipped to 88% last night.\n"
        "ELAI: That must have felt scary to notice. "
        "It looks like it was a brief dip, but I understand why it worried you. "
        "Let’s keep an eye on tonight’s readings and I’ll check back in with you. <END>\n\n"
    )

    instr = (
        "Respond with empathy and understanding. "
        "Do not rush to solutions. "
        "End your response with the token <END>."
    )

    user_line = f"User: {user_text}\nELAI:"

    prompt = system + few_shot + instr + "\n\n" + user_line

    enc = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024,
        padding=True
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            input_ids=enc["input_ids"],
            attention_mask=enc["attention_mask"],
            max_new_tokens=160,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.05,
            pad_token_id=getattr(tokenizer, "pad_token_id", getattr(tokenizer, "eos_token_id", None)),
            eos_token_id=getattr(tokenizer, "eos_token_id", None),
            use_cache=True
        )

    generated_ids = out[0][enc["input_ids"].shape[1]:]
    raw = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    if "<END>" in raw:
        final = raw.split("<END>")[0].strip()
    else:
        final = raw.strip()

    final = re.sub(r"\s+", " ", final).strip()
    final = final.rstrip(" ,;:")

    if not re.search(r"[.!?]$", final):
        final += "."

    return final

import re, torch
from transformers import AutoTokenizer, AutoModelForCausalLM

FINETUNED_MODEL_PATH = "/root/.cache/huggingface/hub/models--HuggingFaceH4--zephyr-7b-beta/snapshots/892b3d7a7b1cf10c7a701c60881cd93df615734c"

tokenizer = AutoTokenizer.from_pretrained(
    FINETUNED_MODEL_PATH,
    use_fast=False,
    trust_remote_code=True,
    local_files_only=True
)

model = AutoModelForCausalLM.from_pretrained(
    FINETUNED_MODEL_PATH,
    trust_remote_code=True,
    device_map="auto",
    local_files_only=True
)

model.eval()

def generate_elai_final(user_text, user_name=None):
    if not user_text or str(user_text).strip() == "":
        return "I’m here with you. Whenever you’re ready, tell me what’s going on."

    system = (
        "System: You are ELAI, a calm, warm, deeply empathetic wellness companion. "
        "You speak like a caring human, not a machine or doctor. "
        "First, acknowledge and validate the user’s feelings. "
        "Second, reflect what you understood in simple words. "
        "Third, offer one or two gentle, realistic ideas they could try. "
        "Keep the tone soft, supportive, and conversational. Avoid clinical language.\n"
    )

    few_shot = (
        "User: I tried meditation but I couldn't focus.\n"
        "ELAI: That can feel really discouraging, especially when you’re trying to help yourself. "
        "It’s completely normal for the mind to wander, especially at the beginning. "
        "You could try something lighter today, like a slow walk or just noticing your breathing for a minute or two. <END>\n\n"
        "User: My oxygen dipped to 88% last night.\n"
        "ELAI: That sounds unsettling, and it makes sense that it worried you. "
        "From what you shared, it seems like it was a brief dip, but it’s okay to stay cautious. "
        "Let’s keep an eye on tonight’s readings together, and if it keeps happening, we can think about the next step. <END>\n\n"
    )

    instr = (
        "Respond in a warm, human way. "
        "Aim for 4 to 6 sentences. "
        "Be empathetic and reassuring, not rushed. "
        "When you have fully answered, end with the token <END> and nothing after it."
    )

    user_line = (
        f"User ({user_name}): {user_text}\nELAI:"
        if user_name
        else f"User: {user_text}\nELAI:"
    )

    prompt = system + few_shot + instr + "\n\n" + user_line

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024,
        padding=True
    )

    device = next(model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_new_tokens=220,
            do_sample=True,
            temperature=0.75,
            top_p=0.9,
            repetition_penalty=1.05,
            eos_token_id=getattr(tokenizer, "eos_token_id", None),
            use_cache=True
        )

    generated_ids = out[0][inputs["input_ids"].shape[1]:]
    raw = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    if "<END>" in raw:
        final = raw.split("<END>")[0].strip()
    else:
        final = raw.strip()

    final = re.sub(r"\s+", " ", final).strip()
    final = final.rstrip(" ,;:")

    return final

print(generate_elai_final("I tried meditation, but I couldn’t focus at all."))

import re, torch

def generate_elai_final(user_text: str, user_name: str | None = None) -> str:
    if not user_text or str(user_text).strip() == "":
        return "I’m here with you. Whenever you feel ready, you can tell me what’s going on."

    system = (
        "System: You are ELAI, a calm, warm, deeply empathetic wellness companion. "
        "You speak like a caring human friend, not a doctor. "
        "First, gently acknowledge and validate how the user feels. "
        "Second, reflect back what you understood in simple words. "
        "Third, offer one or two gentle, realistic next steps if appropriate. "
        "Keep responses warm, grounded, and conversational. "
        "Avoid clinical language, diagnoses, or medication advice. "
        "Respond in 3 to 6 short sentences. "
        "When you are done, end with the token <END>."
    )

    few_shot = (
        "User: I tried meditation but I couldn't focus.\n"
        "ELAI: That can feel really discouraging, especially when you were genuinely trying to calm your mind. "
        "A wandering mind doesn’t mean you failed — it’s actually very common. "
        "You might try something lighter, like noticing your breath for just one minute or stretching slowly, instead. <END>\n\n"
        "User: My oxygen dipped to 88% last night and it scared me.\n"
        "ELAI: That sounds frightening, and it makes sense that it worried you. "
        "From what you’re describing, it seems like a brief dip, but your concern is valid. "
        "Let’s keep an eye on tonight’s readings together, and if this keeps happening or you feel unwell, reaching out to a doctor would be a good next step. <END>\n\n"
    )

    if user_name:
        user_line = f"User ({user_name}): {user_text}\nELAI:"
    else:
        user_line = f"User: {user_text}\nELAI:"

    prompt = system + "\n\n" + few_shot + user_line

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024,
        padding=True,
    )

    device = next(model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_new_tokens=220,
            do_sample=True,
            temperature=0.6,
            top_p=0.85,
            repetition_penalty=1.05,
            eos_token_id=getattr(tokenizer, "eos_token_id", None),
            early_stopping=True,
            use_cache=True,
        )

    generated_ids = out[0][inputs["input_ids"].shape[1]:]
    raw = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()

    if "<END>" in raw:
        final = raw.split("<END>")[0].strip()
    else:
        final = raw.strip()

    final = re.sub(r"\s+", " ", final).strip()
    final = final.rstrip(" ,;:")

    return final

import re

def route_elai_response(user_text: str):
    if not user_text or not user_text.strip():
        return "I'm here with you. When you're ready, tell me what's going on."

    t = user_text.lower()

    emergency_triggers = [
        "chest pain", "can't breathe", "cannot breathe", "breathless",
        "oxygen dropped", "spo2", "heart attack", "fainted", "collapsed",
        "i'm dying", "i am dying", "call emergency", "help me now",
        "suicidal", "i want to die", "don't want to live", "kill myself"
    ]

    warning_triggers = [
        "dizzy", "lightheaded", "palpitations", "panic attack",
        "heart racing", "tight chest", "shortness of breath",
        "fell down", "fall detected", "low oxygen"
    ]

    if any(k in t for k in emergency_triggers):
        return (
            "I’m really glad you reached out. What you’re describing could be serious, "
            "and your safety matters most right now. Please contact emergency services "
            "or a trusted person immediately and seek medical help."
        )

    if any(k in t for k in warning_triggers):
        return generate_elai_final(
            "The user is experiencing possible physical distress: " + user_text
        )

    return generate_elai_final(user_text)

import re, torch

def generate_elai_final(user_text, user_name=None):
    if not user_text or user_text.strip() == "":
        return "I’m here with you."

    system = (
        "System: You are ELAI, a warm, empathetic wellness companion. "
        "You speak like a caring human, not a therapist or assistant. "
        "Do not explain, analyze, or paraphrase the user. "
        "Do not use phrases like 'it sounds like', 'you are experiencing', or 'it is understandable'. "
        "First acknowledge the feeling in a human way. "
        "Then gently sit with them. "
        "Then offer ONE soft wellness suggestion as an invitation, not advice. "
        "Keep the response short, calm, and conversational."
    )

    prompt = system + "\n\n" + (
        f"User: {user_text}\nELAI:"
        if not user_name
        else f"User ({user_name}): {user_text}\nELAI:"
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512,
        padding=True
    )

    device = next(model.parameters()).device
    inputs = {k: v.to(device) for k, v in inputs.items()}

    with torch.no_grad():
        out = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_new_tokens=45,
            do_sample=True,
            temperature=0.5,
            top_p=0.75,
            repetition_penalty=1.2,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.eos_token_id,
            use_cache=True
        )

    text = tokenizer.decode(
        out[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    ).strip()

    sentences = re.split(r'(?<=[.!?])\s+', text)
    final = " ".join(sentences[:2]).strip()

    final = re.sub(
        r"\b(it sounds like|you are experiencing|it is understandable|would you like me to)\b",
        "",
        final,
        flags=re.IGNORECASE
    ).strip()

    if not re.search(r'[.!?]$', final):
        final += "."

    return final

def elai_core(user_text, sensor_data=None):
    sensor_context = build_sensor_context(sensor_data)

    combined_input = (
        sensor_context
        + "\n\nUser says: "
        + user_text
    )

    reply = generate_elai_final(combined_input)

    return reply

import os

os.environ["ELEVEN_API_KEY"] = "sk_70b209d4595e802607414e5215c85fd3f3c625efb22dd2f1"

import os, requests, tempfile
from IPython.display import Audio, display

ELEVEN_API_KEY = os.environ.get("ELEVEN_API_KEY")
VOICE_ID = os.environ.get("ELEVEN_VOICE_ID", "EXAVITQu4vr4xnSDxMaL")
MODEL_ID = "eleven_multilingual_v2"

def elai_tts(text):
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
    headers = {
        "xi-api-key": ELEVEN_API_KEY,
        "Content-Type": "application/json"
    }
    payload = {
        "text": text,
        "model_id": MODEL_ID,
        "voice_settings": {
            "stability": 0.55,
            "similarity_boost": 0.7,
            "style": 0.35,
            "use_speaker_boost": True
        }
    }
    r = requests.post(url, headers=headers, json=payload)
    r.raise_for_status()
    tmp = tempfile.mktemp(suffix=".mp3")
    with open(tmp, "wb") as f:
        f.write(r.content)
    return tmp

def elai_voice_reply(user_text):
    reply = generate_elai_final(user_text)
    audio_path = elai_tts(reply)
    display(Audio(audio_path, autoplay=True))
    return reply

elai_voice_reply("I feel anxious and couldn’t sleep properly last night.")

!pip install -U --no-cache-dir openai-whisper

!pip uninstall -y whisper whisper-openai openai_whisper
!pip install --no-cache-dir openai-whisper

import whisper
print("Whisper loaded:", hasattr(whisper, "load_model"))

import gradio as gr
import torch, re, tempfile, requests, os, soundfile as sf, whisper

ELEVEN_API_KEY = os.environ.get("ELEVEN_API_KEY")
VOICE_ID = "EXAVITQu4vr4xnSDxMaL"

whisper_model = whisper.load_model("base")

session_memory = {}

def clean_reply(text):
    text = re.split(r"\b(User:|ELAI:)\b", text)[0]
    text = re.sub(r"\s+", " ", text).strip()
    if not re.search(r"[.!?]$", text):
        text += "."
    return text

def build_prompt(user_text, history):
    context = ""
    for u, a in history[-2:]:
        context += f"User: {u}\nELAI: {a}\n"
    return (
        "System: You are ELAI, a calm, warm, empathetic wellness companion. "
        "Acknowledge feelings first, then gently help. "
        "Be conversational, supportive, and complete.\n\n"
        + context +
        f"User: {user_text}\nELAI:"
    )

def generate_elai_reply(user_text, session_id):
    history = session_memory.get(session_id, [])
    prompt = build_prompt(user_text, history)

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=1024,
        padding=True
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            max_new_tokens=120,
            do_sample=True,
            temperature=0.7,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    raw = tokenizer.decode(
        out[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    )

    reply = clean_reply(raw)
    history.append((user_text, reply))
    session_memory[session_id] = history[-6:]

    return reply

def eleven_tts(text):
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
    headers = {
        "xi-api-key": ELEVEN_API_KEY,
        "Content-Type": "application/json"
    }
    payload = {
        "text": text,
        "voice_settings": {
            "stability": 0.35,
            "similarity_boost": 0.8,
            "style": 0.7,
            "use_speaker_boost": True
        }
    }
    r = requests.post(url, headers=headers, json=payload)
    r.raise_for_status()
    tmp = tempfile.mktemp(suffix=".mp3")
    with open(tmp, "wb") as f:
        f.write(r.content)
    return tmp

def text_chat(user_text, session_id):
    return generate_elai_reply(user_text, session_id)

def text_to_speech(user_text, session_id):
    reply = generate_elai_reply(user_text, session_id)
    audio = eleven_tts(reply)
    return audio, reply

def speech_to_speech(audio, session_id):
    text = whisper_model.transcribe(audio)["text"].strip()
    reply = generate_elai_reply(text, session_id)
    audio_out = eleven_tts(reply)
    return audio_out, f"User: {text}\n\nELAI: {reply}"

with gr.Blocks() as demo:
    sid = gr.State(lambda: os.urandom(8).hex())

    gr.Markdown("# ELAI — Empathetic Voice & Text Companion")

    with gr.Tab("Text → Text"):
        t1 = gr.Textbox(lines=3)
        b1 = gr.Button("Ask")
        o1 = gr.Textbox(lines=6)
        b1.click(text_chat, inputs=[t1, sid], outputs=o1)

    with gr.Tab("Text → Speech"):
        t2 = gr.Textbox(lines=3)
        b2 = gr.Button("Speak")
        o2a = gr.Audio(type="filepath")
        o2t = gr.Textbox(lines=6)
        b2.click(text_to_speech, inputs=[t2, sid], outputs=[o2a, o2t])

    with gr.Tab("Speech → Speech"):
        mic = gr.Audio(sources=["microphone"], type="filepath")
        b3 = gr.Button("Talk")
        o3a = gr.Audio(type="filepath")
        o3t = gr.Textbox(lines=8)
        b3.click(speech_to_speech, inputs=[mic, sid], outputs=[o3a, o3t])

demo.launch(share=True)